package client.view;

import client.modelo.Autenticacao;
import client.persistencia.Arquivos;
import java.sql.*;
import javax.swing.*;
import java.io.*;

/*
 Descrição: Tela principal do cliente
 */
public class TelaPrincipal extends javax.swing.JFrame implements Serializable {

    // Variável para armazenamento dos dados de autenticação do banco de dados.
    public Autenticacao autenticacao;

    /*
     Descrição: Construtor padrão da janela principal.
     Parâmetros:
     Retorno:
     */
    public TelaPrincipal() {
        initComponents();
        this.setIconImage(new ImageIcon("../Imagens/pedaco_pizza.png").getImage());
        this.abrirPedido.setEnabled(false);
        verificarAutenticacao();
    }

    /*
     Descrição: Método para tentativa de autenticação dos dados do banco de dados.
     Parâmetros:
     Retorno:
     */
    public void verificarAutenticacao() {
        Arquivos arquivo = new Arquivos();
        try {
            autenticacao = arquivo.lerArquivo();
            try {
                // Se a conexão foi efetuada, o botão de autenticação é desabilitado e o botão para abrir pedido é habilitado.
                Connection conexao = DriverManager.getConnection(autenticacao.getCaminhoBanco(), autenticacao.getUsuarioBanco(), autenticacao.getUsuarioSenha());
                conexao.close();
                this.autenticar.setVisible(false);
                this.abrirPedido.setEnabled(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Não foi possível autenticar a conexão.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sairAplicacao = new javax.swing.JButton();
        abrirPedido = new javax.swing.JButton();
        autenticar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OpenPizza");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        sairAplicacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sairAplicacao.setText("Sair");
        sairAplicacao.setPreferredSize(new java.awt.Dimension(110, 30));
        sairAplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairAplicacaoActionPerformed(evt);
            }
        });

        abrirPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        abrirPedido.setText("Abrir Pedido");
        abrirPedido.setPreferredSize(new java.awt.Dimension(110, 30));
        abrirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPedidoActionPerformed(evt);
            }
        });

        autenticar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        autenticar.setText("Autenticar");
        autenticar.setPreferredSize(new java.awt.Dimension(110, 30));
        autenticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autenticarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/view/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(autenticar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abrirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sairAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(autenticar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(abrirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(sairAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     Descrição: Método do botão Sair
     Parâmetros:
     Retorno:
     */
    private void sairAplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairAplicacaoActionPerformed
        // Saída da aplicação
        System.exit(0);
    }//GEN-LAST:event_sairAplicacaoActionPerformed

    /*
     Descrição: Método para criação da janela de pedido após a autenticação do banco de dados
     Parâmetros:
     Retorno:
     */
    private void abrirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPedidoActionPerformed
        // Criação da janela de pedido
        TelaPedido janelaPedido = new TelaPedido(this, this.autenticacao);
        this.setVisible(false);
        janelaPedido.setResizable(false);
        janelaPedido.setSize(350, 600);
        janelaPedido.setLocation(50, 70);
        janelaPedido.setVisible(true);
    }//GEN-LAST:event_abrirPedidoActionPerformed

    /*
     Descrição: Método para criação da janela de autenticação do banco de dados.
     Parâmetros:
     Retorno:
     */
    private void autenticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autenticarActionPerformed
        // Criação da janela de autenticação
        TelaAutenticacao janelaAutenticar = new TelaAutenticacao(this, this.abrirPedido, this.autenticar);
        janelaAutenticar.setVisible(true);
        janelaAutenticar.setLocation(50, 70);

    }//GEN-LAST:event_autenticarActionPerformed

    /*
     Descrição: Método executado ao clicar no Fechar (X).
     Parâmetros:
     Retorno:
     */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // Fechar a aplicação
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirPedido;
    private javax.swing.JButton autenticar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton sairAplicacao;
    // End of variables declaration//GEN-END:variables
}
