// Pacote View
package server.view;

// Importação dos pacotes necessários
import server.controle.Controle;
import server.modelo.Autenticacao;

/*
 Descrição: Tela de Exibição de Produtos Cadastrados
 */
public class TelaExibirProdutosCadastrados extends javax.swing.JFrame {

    // Variáveis encapsuladas
    private Autenticacao autenticacao;
    private Controle controle;

    /*
     Descrição: Construtor padrão da Tela de Exibição de Produtos Cadastrados
     Parâmetros:
     Retorno:
     */
    private TelaExibirProdutosCadastrados() {
        initComponents();
    }

    /*
     Descrição: Construtor completo da Tela de Exibição de Pedidos em Aberto
     Parâmetros:
     autenticacao (Objeto do tipo Autenticacao contendo informações para acesso ao banco de dados)
     controle (Objeto do tipo Controle)
     Retorno:
     */
    public TelaExibirProdutosCadastrados(Autenticacao autenticacao, Controle controle) {
        this();
        this.setAutenticacao(autenticacao);
        this.setControle(controle);
        this.painelProdutosMouseClicked(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        botaoVoltar = new javax.swing.JButton();
        painelProdutos = new javax.swing.JTabbedPane();
        painelPizzas = new javax.swing.JScrollPane();
        tabelaPizzas = new javax.swing.JTable();
        painelLanches = new javax.swing.JScrollPane();
        tabelaLanches = new javax.swing.JTable();
        painelBebidas = new javax.swing.JScrollPane();
        tabelaBebidas = new javax.swing.JTable();
        painelOutros = new javax.swing.JScrollPane();
        tabelaOutros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OpenPizza - Produtos Cadastrados");
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        botaoVoltar.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/view/icones_CRUD/voltar.png"))); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.setMaximumSize(new java.awt.Dimension(130, 80));
        botaoVoltar.setMinimumSize(new java.awt.Dimension(130, 80));
        botaoVoltar.setPreferredSize(new java.awt.Dimension(130, 80));
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        painelProdutos.setFont(new java.awt.Font("Cantarell", 0, 17)); // NOI18N
        painelProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelProdutosMouseClicked(evt);
            }
        });

        tabelaPizzas.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        tabelaPizzas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaPizzas.setRowHeight(25);
        tabelaPizzas.setRowMargin(5);
        painelPizzas.setViewportView(tabelaPizzas);

        painelProdutos.addTab("Pizzas", painelPizzas);

        tabelaLanches.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        tabelaLanches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaLanches.setRowHeight(25);
        tabelaLanches.setRowMargin(5);
        painelLanches.setViewportView(tabelaLanches);

        painelProdutos.addTab("Lanches", painelLanches);

        tabelaBebidas.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        tabelaBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaBebidas.setRowHeight(25);
        tabelaBebidas.setRowMargin(5);
        painelBebidas.setViewportView(tabelaBebidas);

        painelProdutos.addTab("Bebidas", painelBebidas);

        tabelaOutros.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        tabelaOutros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaOutros.setRowHeight(25);
        tabelaOutros.setRowMargin(5);
        painelOutros.setViewportView(tabelaOutros);

        painelProdutos.addTab("Outros", painelOutros);

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*
     Descrição: Evento ao clicar no botão Voltar
     Parâmetros:
     Retorno:
     */
    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // Fechar janela atual
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /*
     Descrição: Evento ao clicar no painel de produtos (Exibição dos produtos de acordo com a categoria)
     Parâmetros:
     Retorno:
     */
    private void painelProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelProdutosMouseClicked
        // Recuperação e exibição dos produtos cadastrados
        switch (this.painelProdutos.getSelectedIndex()) {
            case 0:
                this.getControle().consultarCardapio(this.getAutenticacao(), this.tabelaPizzas, "Pizza");
                break;

            case 1:
                this.getControle().consultarCardapio(this.getAutenticacao(), this.tabelaLanches, "Lanche");
                break;

            case 2:
                this.getControle().consultarCardapio(this.getAutenticacao(), this.tabelaBebidas, "Bebida");
                break;

            case 3:
                this.getControle().consultarCardapio(this.getAutenticacao(), this.tabelaOutros, "Outro");
                break;
        }
    }//GEN-LAST:event_painelProdutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExibirProdutosCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExibirProdutosCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExibirProdutosCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExibirProdutosCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExibirProdutosCadastrados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JPanel painel;
    private javax.swing.JScrollPane painelBebidas;
    private javax.swing.JScrollPane painelLanches;
    private javax.swing.JScrollPane painelOutros;
    private javax.swing.JScrollPane painelPizzas;
    private javax.swing.JTabbedPane painelProdutos;
    private javax.swing.JTable tabelaBebidas;
    private javax.swing.JTable tabelaLanches;
    private javax.swing.JTable tabelaOutros;
    private javax.swing.JTable tabelaPizzas;
    // End of variables declaration//GEN-END:variables

    /*
     Descrição: Método set para a variável autenticação.
     Parâmetros: 
     autenticacao (Caminho para o banco de dados)
     Retorno:
     */
    public void setAutenticacao(Autenticacao autenticacao) {
        this.autenticacao = autenticacao;
    }

    /*
     Descrição: Método get para a variável autenticação
     Parâmetros:
     Retorno: 
     autenticacao (Objeto do tipo Autenticação com os dados de acesso ao banco de dados)
     */
    public Autenticacao getAutenticacao() {
        return autenticacao;
    }

    /*
     Descrição: Método get do controle
     Parâmetros:
     Retorno:
     controle (Objeto do tipo Controle)
     */
    public Controle getControle() {
        return controle;
    }

    /*
     Descrição: Método set do controle
     Parâmetros:
     controle (Objeto do tipo Controle)
     Retorno:
     */
    public void setControle(Controle controle) {
        this.controle = controle;
    }
}
