/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;
import server.controle.Controle;
import server.modelo.Autenticacao;
import server.persistencia.Banco;

/**
 *
 * @author Gustavo
 */
public class TelaCRUDBebidas extends javax.swing.JFrame {

    /**
     * Creates new form TelaCRUDBebidas
     */
    // Variável para armazenamento da tela principal.
    private TelaPrincipal janelaPrincipal;
    private Controle controle;
    private Autenticacao autenticacaoServer;
    
    /*
     Descrição: Construtor padrão da janela de CRUD Lanches.
     Parâmetros:
     Retorno:
     Data Última Alteração: 22/05/2014
     */
    public TelaCRUDBebidas() {
        initComponents();
    }

    /*
     Descrição: Construtor completo da janela de CRUD de Lanches.
     Parâmetros: janelaPrincipal (Necessário para controle dos métodos da janela anterior)
     *          autenticacao (Necessário para realizar operações no banco de dados)
     Retorno:
     Data Última Alteração: 22/05/2014 
     */
    TelaCRUDBebidas(TelaPrincipal janelaPrincipal, Autenticacao autenticacaoServer) {
        this();
        this.setJanelaPrincipal(janelaPrincipal);        
        this.getJanelaPrincipal().setEnabled(false);
        controle = new Controle();
        controle.exibirBebidasCadastrados(autenticacaoServer, tabelaBebidas);
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /*
     Descrição: Método set para a variável janelaPrincipal.
     Parâmetros: 
     *           janelaPrincipal (Necessário para controle dos métodos da janela principal)
     Retorno:
     Data Última Alteração: 22/05/2014
     */
    public void setJanelaPrincipal(TelaPrincipal janelaPrincipal) {
        this.janelaPrincipal = janelaPrincipal;
    }

    /*
     Descrição: Método get para a variável janelaPrincipal
     Parâmetros:
     Retorno:
     *           janelaPrincipal (Necessário para controle dos métodos da janela anterior)
     Data Última Alteração: 22/05/2014 
     */
    public TelaPrincipal getJanelaPrincipal() {
        return janelaPrincipal;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        jPanelMenuCRUDBebidas = new javax.swing.JPanel();
        botaoAdicionar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        labelVoltar = new javax.swing.JLabel();
        labelAdicionar = new javax.swing.JLabel();
        labelExcluir = new javax.swing.JLabel();
        labelAtualizar = new javax.swing.JLabel();
        painelBebidas = new javax.swing.JScrollPane();
        tabelaBebidas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OpenPizza - Bebidas");
        setBounds(new java.awt.Rectangle(0, 0, 400, 380));
        setMaximumSize(new java.awt.Dimension(540, 400));
        setMinimumSize(new java.awt.Dimension(540, 400));
        setPreferredSize(new java.awt.Dimension(540, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanelMenuCRUDBebidas.setPreferredSize(new java.awt.Dimension(353, 85));

        botaoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/view/icones_CRUD/AdicionarPizza.png"))); // NOI18N
        botaoAdicionar.setContentAreaFilled(false);
        botaoAdicionar.setDefaultCapable(false);
        botaoAdicionar.setMaximumSize(new java.awt.Dimension(63, 63));
        botaoAdicionar.setMinimumSize(new java.awt.Dimension(63, 63));
        botaoAdicionar.setPreferredSize(new java.awt.Dimension(63, 63));
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/view/icones_CRUD/DeleterPizza.png"))); // NOI18N
        botaoExcluir.setBorderPainted(false);
        botaoExcluir.setContentAreaFilled(false);
        botaoExcluir.setMaximumSize(new java.awt.Dimension(63, 63));
        botaoExcluir.setMinimumSize(new java.awt.Dimension(63, 63));
        botaoExcluir.setPreferredSize(new java.awt.Dimension(63, 63));
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/view/icones_CRUD/voltar.png"))); // NOI18N
        botaoVoltar.setBorderPainted(false);
        botaoVoltar.setContentAreaFilled(false);
        botaoVoltar.setMaximumSize(new java.awt.Dimension(63, 63));
        botaoVoltar.setMinimumSize(new java.awt.Dimension(63, 63));
        botaoVoltar.setPreferredSize(new java.awt.Dimension(63, 63));
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/view/icones_CRUD/AtualizaPizza.png"))); // NOI18N
        botaoAtualizar.setBorderPainted(false);
        botaoAtualizar.setContentAreaFilled(false);
        botaoAtualizar.setMaximumSize(new java.awt.Dimension(63, 63));
        botaoAtualizar.setMinimumSize(new java.awt.Dimension(63, 63));
        botaoAtualizar.setPreferredSize(new java.awt.Dimension(63, 63));
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });

        labelVoltar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelVoltar.setText("Voltar");

        labelAdicionar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelAdicionar.setText("Adicionar");

        labelExcluir.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelExcluir.setText("Excluir");

        labelAtualizar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelAtualizar.setText("Atualizar");

        javax.swing.GroupLayout jPanelMenuCRUDBebidasLayout = new javax.swing.GroupLayout(jPanelMenuCRUDBebidas);
        jPanelMenuCRUDBebidas.setLayout(jPanelMenuCRUDBebidasLayout);
        jPanelMenuCRUDBebidasLayout.setHorizontalGroup(
            jPanelMenuCRUDBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuCRUDBebidasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMenuCRUDBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuCRUDBebidasLayout.createSequentialGroup()
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMenuCRUDBebidasLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(labelVoltar)
                        .addGap(18, 18, 18)
                        .addComponent(labelAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(labelExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelAtualizar)))
                .addGap(45, 45, 45))
        );
        jPanelMenuCRUDBebidasLayout.setVerticalGroup(
            jPanelMenuCRUDBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelMenuCRUDBebidasLayout.createSequentialGroup()
                .addGroup(jPanelMenuCRUDBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMenuCRUDBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVoltar)
                    .addComponent(labelAdicionar)
                    .addComponent(labelExcluir)
                    .addComponent(labelAtualizar))
                .addContainerGap())
        );

        tabelaBebidas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tabelaBebidas.setRowHeight(25);
        tabelaBebidas.setRowMargin(5);
        painelBebidas.setViewportView(tabelaBebidas);

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jPanelMenuCRUDBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanelMenuCRUDBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed

        this.getJanelaPrincipal().setVisible(true);
        this.getJanelaPrincipal().setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        int codigoProduto = (Integer) this.tabelaBebidas.getValueAt(this.tabelaBebidas.getSelectedRow(), 0);
        if (codigoProduto > -1) {
            JOptionPane.showMessageDialog(null, "Deseja excluir o item selecionado?", "Confirmação", JOptionPane.QUESTION_MESSAGE);
            System.out.println(codigoProduto);
            //boolean status = banco.excluirProduto(this.getAutenticacaoServer(), codigoProduto);
            
        }

    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        // TODO add your handling code here:
        TelaAdicionarBebidas addBebida = new TelaAdicionarBebidas(this, this.autenticacaoServer);
        addBebida.setVisible(true);
        this.setEnabled(false);
        addBebida.setLocationRelativeTo(null);
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        controle.exibirBebidasCadastrados(this.autenticacaoServer, this.tabelaBebidas);
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.dispose();
        this.getJanelaPrincipal().setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCRUDBebidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JPanel jPanelMenuCRUDBebidas;
    private javax.swing.JLabel labelAdicionar;
    private javax.swing.JLabel labelAtualizar;
    private javax.swing.JLabel labelExcluir;
    private javax.swing.JLabel labelVoltar;
    private javax.swing.JPanel painel;
    private javax.swing.JScrollPane painelBebidas;
    private javax.swing.JTable tabelaBebidas;
    // End of variables declaration//GEN-END:variables
}
