// Pacote View
package server.view;

// Importação dos pacotes e bibliotecas necessárias
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import server.controle.Controle;
import server.modelo.Autenticacao;

/*
 Descrição: Tela CRUD de Pizzas
 */
public class TelaCRUDPizzas extends javax.swing.JFrame {

    // Variáveis encapsuladas
    private TelaPrincipal janelaPrincipal;
    private Controle controle;
    private Autenticacao autenticacao;

    /*
     Descrição: Construtor padrão da janela de CRUD Pizza.
     Parâmetros:
     Retorno:
     */
    private TelaCRUDPizzas() {
        initComponents();
    }

    /*
     Descrição: Construtor completo da janela de CRUD de pizzas.
     Parâmetros: janelaPrincipal (Necessário para controle dos métodos da janela anterior)
     autenticacao (Necessário para realizar operações no banco de dados)
     Retorno:
     */
    public TelaCRUDPizzas(TelaPrincipal telaPrincipal, Autenticacao autenticacao, Controle controle) {
        this();
        this.setJanelaPrincipal(telaPrincipal);
        this.setAutenticacao(autenticacao);
        this.setControle(controle);
        this.getControle().exibirProdutos(this.getAutenticacao(), tabelaCRUDPizza, "Pizza");
        this.formatarTabelaCRUDPizzas();
    }
    
    /*
     Descrição: Método para formatação da tabela de pizzas
     Parâmetros:
     Retorno:
     */
    public void formatarTabelaCRUDPizzas() {

        DefaultTableCellRenderer centralizarLabel = new DefaultTableCellRenderer();
        centralizarLabel.setHorizontalAlignment(JLabel.CENTER);

        // Coluna Código
        this.tabelaCRUDPizza.getColumnModel().getColumn(0).setCellRenderer(centralizarLabel);
        this.tabelaCRUDPizza.getColumnModel().getColumn(0).setMaxWidth(50);

        // Coluna Descrição
        // Formatação padrão

        // Coluna Preço
        this.tabelaCRUDPizza.getColumnModel().getColumn(2).setCellRenderer(centralizarLabel);
        this.tabelaCRUDPizza.getColumnModel().getColumn(2).setMaxWidth(70);

        // Coluna Tamanho
        this.tabelaCRUDPizza.getColumnModel().getColumn(3).setMaxWidth(100);

        // Coluna Fatias
        this.tabelaCRUDPizza.getColumnModel().getColumn(4).setCellRenderer(centralizarLabel);
        this.tabelaCRUDPizza.getColumnModel().getColumn(4).setMaxWidth(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        painel = new javax.swing.JPanel();
        painelPizzas = new javax.swing.JScrollPane();
        tabelaCRUDPizza = new javax.swing.JTable();
        descricaoPizza = new javax.swing.JLabel();
        jPanelMenuCRUDPizzas = new javax.swing.JPanel();
        botaoExcluir = new javax.swing.JButton();
        botaoAdicionar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        labelAtualizar = new javax.swing.JLabel();
        labelExcluir = new javax.swing.JLabel();
        labelVoltar = new javax.swing.JLabel();
        labelAdicionar = new javax.swing.JLabel();
        textoIngredientes = new javax.swing.JScrollPane();
        textAreaIngredientes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OpenPizza - Pizzas");
        setMaximumSize(new java.awt.Dimension(540, 400));
        setMinimumSize(new java.awt.Dimension(540, 400));
        setPreferredSize(new java.awt.Dimension(540, 400));
        setResizable(false);

        tabelaCRUDPizza.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tabelaCRUDPizza.setRowHeight(25);
        tabelaCRUDPizza.setRowMargin(5);
        tabelaCRUDPizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCRUDPizzaMouseClicked(evt);
            }
        });
        painelPizzas.setViewportView(tabelaCRUDPizza);

        descricaoPizza.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        descricaoPizza.setText("Ingredientes:");

        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/view/icones_CRUD/DeleterPizza.png"))); // NOI18N
        botaoExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoExcluir.setBorderPainted(false);
        botaoExcluir.setContentAreaFilled(false);
        botaoExcluir.setMaximumSize(new java.awt.Dimension(63, 63));
        botaoExcluir.setMinimumSize(new java.awt.Dimension(63, 63));
        botaoExcluir.setPreferredSize(new java.awt.Dimension(63, 63));
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoAdicionar.setForeground(new java.awt.Color(240, 240, 240));
        botaoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/view/icones_CRUD/AdicionarPizza.png"))); // NOI18N
        botaoAdicionar.setBorderPainted(false);
        botaoAdicionar.setContentAreaFilled(false);
        botaoAdicionar.setMaximumSize(new java.awt.Dimension(63, 63));
        botaoAdicionar.setMinimumSize(new java.awt.Dimension(63, 63));
        botaoAdicionar.setPreferredSize(new java.awt.Dimension(63, 63));
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/view/icones_CRUD/voltar.png"))); // NOI18N
        botaoVoltar.setBorderPainted(false);
        botaoVoltar.setContentAreaFilled(false);
        botaoVoltar.setMaximumSize(new java.awt.Dimension(63, 63));
        botaoVoltar.setMinimumSize(new java.awt.Dimension(63, 63));
        botaoVoltar.setPreferredSize(new java.awt.Dimension(63, 63));
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/view/icones_CRUD/AtualizaPizza.png"))); // NOI18N
        botaoAtualizar.setBorderPainted(false);
        botaoAtualizar.setContentAreaFilled(false);
        botaoAtualizar.setDefaultCapable(false);
        botaoAtualizar.setMaximumSize(new java.awt.Dimension(63, 63));
        botaoAtualizar.setMinimumSize(new java.awt.Dimension(63, 63));
        botaoAtualizar.setPreferredSize(new java.awt.Dimension(63, 63));
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });

        labelAtualizar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelAtualizar.setText("Atualizar");

        labelExcluir.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelExcluir.setText("Excluir");

        labelVoltar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelVoltar.setText("Voltar");

        labelAdicionar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelAdicionar.setText("Adicionar");

        javax.swing.GroupLayout jPanelMenuCRUDPizzasLayout = new javax.swing.GroupLayout(jPanelMenuCRUDPizzas);
        jPanelMenuCRUDPizzas.setLayout(jPanelMenuCRUDPizzasLayout);
        jPanelMenuCRUDPizzasLayout.setHorizontalGroup(
            jPanelMenuCRUDPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuCRUDPizzasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuCRUDPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuCRUDPizzasLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(labelVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelAdicionar))
                    .addGroup(jPanelMenuCRUDPizzasLayout.createSequentialGroup()
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMenuCRUDPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMenuCRUDPizzasLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(labelExcluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMenuCRUDPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAtualizar)))
        );
        jPanelMenuCRUDPizzasLayout.setVerticalGroup(
            jPanelMenuCRUDPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuCRUDPizzasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuCRUDPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMenuCRUDPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVoltar)
                    .addComponent(labelAdicionar)
                    .addComponent(labelExcluir)
                    .addComponent(labelAtualizar))
                .addContainerGap())
        );

        textAreaIngredientes.setColumns(20);
        textAreaIngredientes.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        textAreaIngredientes.setLineWrap(true);
        textAreaIngredientes.setRows(5);
        textoIngredientes.setViewportView(textAreaIngredientes);

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textoIngredientes))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jPanelMenuCRUDPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(descricaoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 125, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(descricaoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanelMenuCRUDPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(253, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    /*
     Descrição: Evento ao clicar no botão Atualizar
     Parâmetros:
     Retorno:
     */
    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        // Recuperar e exibir as Pizzas cadastradas
        this.getControle().exibirProdutos(this.getAutenticacao(), tabelaCRUDPizza, "Pizza");
        this.formatarTabelaCRUDPizzas();
        this.textAreaIngredientes.setText(null);
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    /*
     Descrição: Evento ao clicar no botão Voltar
     Parâmetros:
     Retorno:
     */
    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // Fechar janela atual
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /*
     Descrição: Evento ao clicar no botão Adicionar
     Parâmetros:
     Retorno:
     */
    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        // Criar e habilitar a visualização da Tela Adicionar Pizzas
        TelaAdicionarPizzas telaAdicionarPizzas = new TelaAdicionarPizzas(this, this.getAutenticacao(), this.getControle());
        telaAdicionarPizzas.setVisible(true);
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    /*
     Descrição: Evento ao clicar no botão Excluir
     Parâmetros:
     Retorno:
     */
    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        // Confirmação de exclusão
        int indice = this.tabelaCRUDPizza.getSelectedRow();
        if (indice >= 0) {
            int confirmacao = JOptionPane.showConfirmDialog(null, "Deseja excluir o item selecionado?\nEssa operação não poderá ser desfeita.", "Aviso", JOptionPane.OK_CANCEL_OPTION);
            if (confirmacao == JOptionPane.OK_OPTION) {
                int codigoDoProduto = Integer.parseInt(String.valueOf(this.tabelaCRUDPizza.getValueAt(this.tabelaCRUDPizza.getSelectedRow(), 0)));
                if (codigoDoProduto >= 0) {
                    boolean desativarProduto = this.getControle().desativarProduto(this.getAutenticacao(), codigoDoProduto);
                    if (desativarProduto) {
                        JOptionPane.showMessageDialog(null, "Produto excluído com sucesso.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        this.getControle().exibirProdutos(this.getAutenticacao(), tabelaCRUDPizza, "Pizza");
                    } else {
                        JOptionPane.showMessageDialog(null, "Não foi possível excluir o produto selecionado.", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    /*
     Descrição: Evento ao clicar na tabela de Pizzas
     Parâmetros:
     Retorno:
     */
    private void tabelaCRUDPizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCRUDPizzaMouseClicked
        // Recuperar e exibir os ingredientes da pizza
        String nomeDoProduto = String.valueOf(this.tabelaCRUDPizza.getValueAt(this.tabelaCRUDPizza.getSelectedRow(), 1));
        this.getControle().consultarIngredientes(this.textAreaIngredientes, this.getAutenticacao(), "Pizza", nomeDoProduto);
    }//GEN-LAST:event_tabelaCRUDPizzaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDPizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDPizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDPizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDPizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCRUDPizzas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel descricaoPizza;
    private javax.swing.JPanel jPanelMenuCRUDPizzas;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelAdicionar;
    private javax.swing.JLabel labelAtualizar;
    private javax.swing.JLabel labelExcluir;
    private javax.swing.JLabel labelVoltar;
    private javax.swing.JPanel painel;
    private javax.swing.JScrollPane painelPizzas;
    private javax.swing.JTable tabelaCRUDPizza;
    private javax.swing.JTextArea textAreaIngredientes;
    private javax.swing.JScrollPane textoIngredientes;
    // End of variables declaration//GEN-END:variables

    /*
     Descrição: Método set para a variável janelaPrincipal.
     Parâmetros: 
     janelaPrincipal (Necessário para controle dos métodos da janela principal)
     Retorno:
     */
    public void setJanelaPrincipal(TelaPrincipal janelaPrincipal) {
        this.janelaPrincipal = janelaPrincipal;
    }

    /*
     Descrição: Método get para a variável janelaPrincipal
     Parâmetros:
     Retorno:
     janelaPrincipal (Necessário para controle dos métodos da janela anterior)
     */
    public TelaPrincipal getJanelaPrincipal() {
        return janelaPrincipal;
    }

    /*
     Descrição: Método get do controle
     Parâmetros:
     Retorno:
     controle (Objeto do tipo Controle)
     */
    public Controle getControle() {
        return controle;
    }

    /*
     Descrição: Método set do controle
     Parâmetros:
     controle (Objeto do tipo Controle)
     Retorno:
     */
    public void setControle(Controle controle) {
        this.controle = controle;
    }

    /*
     Descrição: Método get da autenticação
     Parâmetros:
     Retorno:
     autenticacao (Objeto do tipo Autenticacao contendo as informações para acesso ao banco de dados)
     */
    public Autenticacao getAutenticacao() {
        return autenticacao;
    }

    /*
     Descrição: Método set da autenticação
     Parâmetros:
     autenticacao (Objeto do tipo Autenticacao contendo as informações para acesso ao banco de dados)
     Retorno:
     */
    public void setAutenticacao(Autenticacao autenticacao) {
        this.autenticacao = autenticacao;
    }
}
