/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package server.view;

import server.modelo.Autenticacao;

/**
 *
 * @author Wellington
 */
public class TelaAdicionarLanches extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdicionarLanches
     */        
    private TelaCRUDLanches telaCrudLanches;
    private Autenticacao autenticacao;
    
    public TelaAdicionarLanches() {
        initComponents();
    }

    public TelaAdicionarLanches(TelaCRUDLanches telaCrudLanches, Autenticacao autenticacao)
    {
        this();
        this.setTelaCrudLanches(telaCrudLanches);
        this.setAutenticacao(autenticacao);
        this.getTelaCrudLanches().setEnabled(false);
    }
    
    public TelaCRUDLanches getTelaCrudLanches() {
        return telaCrudLanches;
    }

    public void setTelaCrudLanches(TelaCRUDLanches telaCrudLanches) {
        this.telaCrudLanches = telaCrudLanches;
    }

    public Autenticacao getAutenticacao() {
        return autenticacao;
    }

    public void setAutenticacao(Autenticacao autenticacao) {
        this.autenticacao = autenticacao;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenuCadastroLanches = new javax.swing.JPanel();
        labelNomeLanche = new javax.swing.JLabel();
        textNomeLanche = new javax.swing.JTextField();
        labelIngredientesLanche = new javax.swing.JLabel();
        textIngredientesLanche = new javax.swing.JTextField();
        labelPrecoLanche = new javax.swing.JLabel();
        textPrecoLanche = new javax.swing.JTextField();
        botaoCadastrar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        labelImagemLanche = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(305, 320));
        setMinimumSize(new java.awt.Dimension(305, 320));
        setPreferredSize(new java.awt.Dimension(305, 320));

        labelNomeLanche.setText("Nome:");

        labelIngredientesLanche.setText("Ingredientes:");

        labelPrecoLanche.setText("R$:");

        botaoCadastrar.setText("Cadastrar");

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        jButton1.setText("Procurar");

        labelImagemLanche.setText("Imagem:");

        javax.swing.GroupLayout jPanelMenuCadastroLanchesLayout = new javax.swing.GroupLayout(jPanelMenuCadastroLanches);
        jPanelMenuCadastroLanches.setLayout(jPanelMenuCadastroLanchesLayout);
        jPanelMenuCadastroLanchesLayout.setHorizontalGroup(
            jPanelMenuCadastroLanchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuCadastroLanchesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuCadastroLanchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuCadastroLanchesLayout.createSequentialGroup()
                        .addGroup(jPanelMenuCadastroLanchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textIngredientesLanche)
                            .addGroup(jPanelMenuCadastroLanchesLayout.createSequentialGroup()
                                .addGroup(jPanelMenuCadastroLanchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelMenuCadastroLanchesLayout.createSequentialGroup()
                                        .addComponent(labelNomeLanche)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textNomeLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelMenuCadastroLanchesLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(labelPrecoLanche)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textPrecoLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(labelImagemLanche)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)))
                                .addGap(0, 17, Short.MAX_VALUE))
                            .addGroup(jPanelMenuCadastroLanchesLayout.createSequentialGroup()
                                .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanelMenuCadastroLanchesLayout.createSequentialGroup()
                        .addComponent(labelIngredientesLanche)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelMenuCadastroLanchesLayout.setVerticalGroup(
            jPanelMenuCadastroLanchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuCadastroLanchesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuCadastroLanchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeLanche)
                    .addComponent(textNomeLanche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMenuCadastroLanchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPrecoLanche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrecoLanche)
                    .addComponent(labelImagemLanche)
                    .addComponent(jButton1))
                .addGap(23, 23, 23)
                .addComponent(labelIngredientesLanche)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textIngredientesLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanelMenuCadastroLanchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenuCadastroLanches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenuCadastroLanches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_botaoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarLanches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarLanches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarLanches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarLanches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionarLanches().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanelMenuCadastroLanches;
    private javax.swing.JLabel labelImagemLanche;
    private javax.swing.JLabel labelIngredientesLanche;
    private javax.swing.JLabel labelNomeLanche;
    private javax.swing.JLabel labelPrecoLanche;
    private javax.swing.JTextField textIngredientesLanche;
    private javax.swing.JTextField textNomeLanche;
    private javax.swing.JTextField textPrecoLanche;
    // End of variables declaration//GEN-END:variables
}
