/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package server.view;

/**
 *
 * @author Gustavo
 */
public class TelaCRUDPizza extends javax.swing.JFrame {

    /**
     * Creates new form TelaCRUDPizza
     */
    public TelaCRUDPizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCRUDPizza = new javax.swing.JTable();
        labelImagemPizza = new javax.swing.JLabel();
        descricaoPizza = new javax.swing.JLabel();
        jPanelMenuCRUDPizzas = new javax.swing.JPanel();
        botaoExcluirCRUDPizzas = new javax.swing.JButton();
        botaoAdicionarCRUDPizzas = new javax.swing.JButton();
        botaoVoltarCRUDPizzas = new javax.swing.JButton();
        botaoEditarCRUDPizzas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD Pizza");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jScrollPane1.setViewportView(tabelaCRUDPizza);

        labelImagemPizza.setText("Imagem");

        descricaoPizza.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descricaoPizza.setText("Descrição:");

        botaoExcluirCRUDPizzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/view/icones_CRUD/DeleterPizza.png"))); // NOI18N
        botaoExcluirCRUDPizzas.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        botaoExcluirCRUDPizzas.setBorderPainted(false);
        botaoExcluirCRUDPizzas.setContentAreaFilled(false);
        botaoExcluirCRUDPizzas.setMaximumSize(new java.awt.Dimension(63, 63));
        botaoExcluirCRUDPizzas.setMinimumSize(new java.awt.Dimension(63, 63));
        botaoExcluirCRUDPizzas.setPreferredSize(new java.awt.Dimension(63, 63));
        botaoExcluirCRUDPizzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirCRUDPizzasActionPerformed(evt);
            }
        });

        botaoAdicionarCRUDPizzas.setForeground(new java.awt.Color(240, 240, 240));
        botaoAdicionarCRUDPizzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/view/icones_CRUD/AdicionarPizza.png"))); // NOI18N
        botaoAdicionarCRUDPizzas.setBorderPainted(false);
        botaoAdicionarCRUDPizzas.setContentAreaFilled(false);
        botaoAdicionarCRUDPizzas.setMaximumSize(new java.awt.Dimension(63, 63));
        botaoAdicionarCRUDPizzas.setMinimumSize(new java.awt.Dimension(63, 63));
        botaoAdicionarCRUDPizzas.setPreferredSize(new java.awt.Dimension(63, 63));

        botaoVoltarCRUDPizzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/view/icones_CRUD/voltar.png"))); // NOI18N
        botaoVoltarCRUDPizzas.setBorderPainted(false);
        botaoVoltarCRUDPizzas.setContentAreaFilled(false);
        botaoVoltarCRUDPizzas.setMaximumSize(new java.awt.Dimension(63, 63));
        botaoVoltarCRUDPizzas.setMinimumSize(new java.awt.Dimension(63, 63));
        botaoVoltarCRUDPizzas.setPreferredSize(new java.awt.Dimension(63, 63));
        botaoVoltarCRUDPizzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarCRUDPizzasActionPerformed(evt);
            }
        });

        botaoEditarCRUDPizzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server/view/icones_CRUD/AtualizaPizza.png"))); // NOI18N
        botaoEditarCRUDPizzas.setBorderPainted(false);
        botaoEditarCRUDPizzas.setContentAreaFilled(false);
        botaoEditarCRUDPizzas.setDefaultCapable(false);
        botaoEditarCRUDPizzas.setMaximumSize(new java.awt.Dimension(63, 63));
        botaoEditarCRUDPizzas.setMinimumSize(new java.awt.Dimension(63, 63));
        botaoEditarCRUDPizzas.setPreferredSize(new java.awt.Dimension(63, 63));
        botaoEditarCRUDPizzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarCRUDPizzasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuCRUDPizzasLayout = new javax.swing.GroupLayout(jPanelMenuCRUDPizzas);
        jPanelMenuCRUDPizzas.setLayout(jPanelMenuCRUDPizzasLayout);
        jPanelMenuCRUDPizzasLayout.setHorizontalGroup(
            jPanelMenuCRUDPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuCRUDPizzasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoVoltarCRUDPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAdicionarCRUDPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoExcluirCRUDPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoEditarCRUDPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanelMenuCRUDPizzasLayout.setVerticalGroup(
            jPanelMenuCRUDPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuCRUDPizzasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuCRUDPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoExcluirCRUDPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdicionarCRUDPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltarCRUDPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEditarCRUDPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descricaoPizza)
                            .addComponent(labelImagemPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jPanelMenuCRUDPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelImagemPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descricaoPizza)
                        .addGap(191, 191, 191)
                        .addComponent(jPanelMenuCRUDPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarCRUDPizzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarCRUDPizzasActionPerformed
        // TODO add your handling code here:
        TelaPrincipal tPrincipal = new TelaPrincipal();
        this.dispose();
    }//GEN-LAST:event_botaoVoltarCRUDPizzasActionPerformed

    private void botaoExcluirCRUDPizzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirCRUDPizzasActionPerformed
       //System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_botaoExcluirCRUDPizzasActionPerformed

    private void botaoEditarCRUDPizzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarCRUDPizzasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEditarCRUDPizzasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCRUDPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCRUDPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionarCRUDPizzas;
    private javax.swing.JButton botaoEditarCRUDPizzas;
    private javax.swing.JButton botaoExcluirCRUDPizzas;
    private javax.swing.JButton botaoVoltarCRUDPizzas;
    private javax.swing.JLabel descricaoPizza;
    private javax.swing.JPanel jPanelMenuCRUDPizzas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelImagemPizza;
    private javax.swing.JTable tabelaCRUDPizza;
    // End of variables declaration//GEN-END:variables
}
