/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package server.view;

import java.sql.Connection;
import javax.swing.JOptionPane;
import server.modelo.Autenticacao;
import server.persistencia.Banco;

/**
 *
 * @author Wellington
 */
public class TelaAdicionarOutros extends javax.swing.JFrame {

    private TelaCRUDOutros telaCrudOutros;
    private Banco bancoDados = new Banco();
    private Connection connection;
    private Autenticacao autenticacaoServer;
    private String descricaoOutros;
    private String precoOutros;
    private float precoOutrosFinal;
    
    public TelaAdicionarOutros() {
        initComponents();
    }

    public TelaAdicionarOutros(TelaCRUDOutros telaCrudOutros, Autenticacao autenticacaoServer)            
    {
        this();        
        this.setAutenticacaoServer(autenticacaoServer);
        this.setTelaCrudOutros(telaCrudOutros);
    }
    
    public TelaCRUDOutros getTelaCrudOutros() {
        return telaCrudOutros;
    }

    public void setTelaCrudOutros(TelaCRUDOutros telaCrudOutros) {
        this.telaCrudOutros = telaCrudOutros;
    }

    public Banco getBancoDados() {
        return bancoDados;
    }

    public void setBancoDados(Banco bancoDados) {
        this.bancoDados = bancoDados;
    }

    public Autenticacao getAutenticacaoServer() {
        return autenticacaoServer;
    }

    public void setAutenticacaoServer(Autenticacao autenticacaoServer) {
        this.autenticacaoServer = autenticacaoServer;
    }

    public String getDescricaoOutros() {
        return descricaoOutros;
    }

    public void setDescricaoOutros(String descricaoOutros) {
        this.descricaoOutros = descricaoOutros;
    }

    public String getPrecoOutros() {
        return precoOutros;
    }

    public void setPrecoOutros(String precoOutros) {
        this.precoOutros = precoOutros;
    }

    public float getPrecoOutrosFinal() {
        return precoOutrosFinal;
    }

    public void setPrecoOutrosFinal(float precoOutrosFinal) {
        this.precoOutrosFinal = precoOutrosFinal;
    }            
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCadastrarOutros = new javax.swing.JPanel();
        labelDescricaoOutros = new javax.swing.JLabel();
        textDescricaoOutros = new javax.swing.JTextField();
        labelPrecoOutros = new javax.swing.JLabel();
        textPrecoOutros = new javax.swing.JTextField();
        buttonCadastrarOutros = new javax.swing.JButton();
        buttonCancelarCadastroOutros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelCadastrarOutros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Outros Produtos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        labelDescricaoOutros.setText("Descrição:");

        textDescricaoOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDescricaoOutrosActionPerformed(evt);
            }
        });

        labelPrecoOutros.setText("Preço:");

        textPrecoOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrecoOutrosActionPerformed(evt);
            }
        });

        buttonCadastrarOutros.setText("Cadastrar");
        buttonCadastrarOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarOutrosActionPerformed(evt);
            }
        });

        buttonCancelarCadastroOutros.setText("Cancelar");
        buttonCancelarCadastroOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarCadastroOutrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCadastrarOutrosLayout = new javax.swing.GroupLayout(painelCadastrarOutros);
        painelCadastrarOutros.setLayout(painelCadastrarOutrosLayout);
        painelCadastrarOutrosLayout.setHorizontalGroup(
            painelCadastrarOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastrarOutrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastrarOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textDescricaoOutros)
                    .addGroup(painelCadastrarOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelDescricaoOutros)
                        .addGroup(painelCadastrarOutrosLayout.createSequentialGroup()
                            .addComponent(labelPrecoOutros)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textPrecoOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelCadastrarOutrosLayout.createSequentialGroup()
                            .addComponent(buttonCadastrarOutros)
                            .addGap(45, 45, 45)
                            .addComponent(buttonCancelarCadastroOutros))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCadastrarOutrosLayout.setVerticalGroup(
            painelCadastrarOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastrarOutrosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelDescricaoOutros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDescricaoOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelCadastrarOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecoOutros)
                    .addComponent(textPrecoOutros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCadastrarOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCadastrarOutros)
                    .addComponent(buttonCancelarCadastroOutros))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(painelCadastrarOutros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(painelCadastrarOutros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textDescricaoOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDescricaoOutrosActionPerformed
        this.setDescricaoOutros(textDescricaoOutros.getText());
    }//GEN-LAST:event_textDescricaoOutrosActionPerformed

    private void textPrecoOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrecoOutrosActionPerformed
        this.setPrecoOutros(textPrecoOutros.getText());
    }//GEN-LAST:event_textPrecoOutrosActionPerformed

    private void buttonCadastrarOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarOutrosActionPerformed
        this.setDescricaoOutros(textDescricaoOutros.getText());
        this.setPrecoOutros(textPrecoOutros.getText());
                
        if(this.getDescricaoOutros().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor preencha o campo 'Descrição'");
        } else if(this.getPrecoOutros().equals("")){
                JOptionPane.showMessageDialog(null, "Preencha o campo 'Preço'");
                } else {
                    this.setPrecoOutrosFinal(Float.parseFloat(textPrecoOutros.getText()));
                    if(this.getPrecoOutrosFinal() <= 0.00){
                        JOptionPane.showMessageDialog(null, "Por favor, preencha com valores Positivos o campo 'Preço'");
                    }
                }
        
        if((!(this.getDescricaoOutros().equals(""))) && (!(this.getPrecoOutros().equals(""))) && (!(this.getPrecoOutrosFinal() <= 0.00))){
            try{
                boolean retorno = bancoDados.inserirOutros(this.getAutenticacaoServer(), this.getDescricaoOutros(), this.getPrecoOutrosFinal());
                if(retorno == true){
                    JOptionPane.showMessageDialog(null, "Outros cadastrada com sucesso!!!");
                }else{
                    JOptionPane.showMessageDialog(null, "Não foi possível cadastrar Outros");
                }                                    
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "Não foi possível cadastrar Outros");
            }
        }                          
        //this.setEnabled(false);
        //this.setVisible(false);
        //this.telaCrudOutros.setEnabled(true);
        //this.telaCrudOutros.setVisible(true);
    }//GEN-LAST:event_buttonCadastrarOutrosActionPerformed

    private void buttonCancelarCadastroOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarCadastroOutrosActionPerformed
        this.setVisible(false);
        this.setEnabled(false);
        this.telaCrudOutros.setVisible(true);
        this.telaCrudOutros.setEnabled(true);
    }//GEN-LAST:event_buttonCancelarCadastroOutrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarOutros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarOutros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarOutros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarOutros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionarOutros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrarOutros;
    private javax.swing.JButton buttonCancelarCadastroOutros;
    private javax.swing.JLabel labelDescricaoOutros;
    private javax.swing.JLabel labelPrecoOutros;
    private javax.swing.JPanel painelCadastrarOutros;
    private javax.swing.JTextField textDescricaoOutros;
    private javax.swing.JTextField textPrecoOutros;
    // End of variables declaration//GEN-END:variables
}
